sonar.projectKey=adam-tasklist-backend
sonar.token=sqp_c0cb7a1c0a6fb298285bd73019f3a96377f5562d
sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr
sonar.projectName=TaskList Backend
sonar.sources=src
sonar.exclusions=src/__tests__/**,src/server.ts,**/*.config.ts
sonar.tests=src/__tests__
sonar.language=ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.junit.reportPaths=reports/junit.xml
